object Versions {
    const val coreKtx = "1.13.1"
    const val lifecycleRuntimeKtx = "2.8.5"
    const val activityCompose = "1.9.2"
    const val composeBom = "2024.04.01"
    const val firebaseBom = "33.7.0"
    const val hilt = "2.50"
    const val okHttp = "4.12.0"
    const val retrofit = "2.11.0"
    const val serializationJson = "1.6.3"
    const val junit = "4.13.2"
    const val junitVersion = "1.2.1"
    const val spotless = "6.20.0"
    const val detekt = "1.23.7"
    const val firebaseCrashlytics = "3.0.2"
    const val gmsGoogleService = "4.4.2"
    const val kotlinGradle = "1.9.21"
    const val kotlinToolGradle = "8.5.0"
    const val kotlinSerialization = "1.9.21"
}